function [param_vec,len] = struct2vec(param)
    param_vec = [param.mu, param.d1, param.R0, param.gamma, ...
        param.turn_dates param.t_trans, param.d2];
    
    % start/stop indices of each param (to recover variables from param_vec)
    len = [length(param.mu),      length(param.d1), ...
        length(param.R0),         length(param.gamma), ...
        length(param.turn_dates), length(param.t_trans), ...
        length(param.d2)];
    len = cumsum(len);
end